### PR TITLE
End files with empty newline

### LINKED ISSUE #64: Question: Trailing newline or not
I use em every day, love it! Makes my life so much easier. I was thinking I should contribute some patches when I have the time.

Anyhow just wanted to check your stance on ending newlines in files. Was it by intention that you removed the ending newline on most files in the latest release?

EM generated files today:
```
Code
Code <- file ends here
```

Better way?:
```
Code
Code 
<- file ends here
```

### PR DESCRIPTION
**Pull request by lirbank**
Fixes #64 and a few other minor (but very annoying) things. 

With regards to 1d4a703b68f9d42686c7da0a51a6e371bb0200eb - I removed the file extension label as I don't find it useful so I assumed it's some legacy code but I could be wrong?

These three commits fixes things that I manually change EVERY time I generate files with EM, so got tired of it and decided to fix it once and for all. Would be awesome to get the changes into the main repo.

### CODE REVIEW

**Comment by lirbank** [comment]
@scott-mcpherson With this fix https://github.com/lirbank/em/commit/e09db34d70996ef37219be33aaf9decd6fb297ff in place, to tidy things would it make sense to remove lines [47 and 49](https://github.com/lirbank/em/blob/e09db34d70996ef37219be33aaf9decd6fb297ff/lib/generator.js#L47)?

**Comment by scott-mcpherson** [comment]
@lirbank It looks like 47 and 49 are no longer needed. Whatever you decide is good with me. Let me know and I'll merge. Thanks!

**Comment by lirbank** [comment]
Great! I've removed the lines 47 and 49. Also committed a few more improvements making templates more consistent.

**Comment by scott-mcpherson** [comment]
Awesome, thanks! I'll be merging this with master and creating a release real soon.

**Pull request merged**
